import jsPDF from 'jspdf';

export const generateLoanPDF = (
  loanAmount: string,
  interestRate: string,
  loanTerm: string,
  monthlyPayment: number,
  totalPayment: number,
  totalInterest: number
) => {
  const doc = new jsPDF();
  
  // Add logo text
  doc.setFontSize(24);
  doc.setTextColor(51, 65, 85); // slate-700
  doc.text("Loan-Calculator.co.uk", 105, 20, { align: "center" });
  
  // Add decorative line
  doc.setDrawColor(99, 102, 241); // indigo-500
  doc.setLineWidth(0.5);
  doc.line(20, 25, 190, 25);

  // Add loan details
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Personal Loan Summary", 105, 40, { align: "center" });

  doc.setFontSize(12);
  const startY = 60;
  const lineHeight = 10;

  doc.text(`Loan Amount: £${Number(loanAmount).toLocaleString()}`, 20, startY);
  doc.text(`Interest Rate: ${interestRate}%`, 20, startY + lineHeight);
  doc.text(`Loan Term: ${loanTerm} years`, 20, startY + lineHeight * 2);
  
  // Add results
  doc.setFontSize(14);
  doc.text("Payment Details", 20, startY + lineHeight * 4);
  
  doc.setFontSize(12);
  doc.text(`Monthly Payment: £${monthlyPayment.toFixed(2)}`, 20, startY + lineHeight * 5);
  doc.text(`Total Interest: £${totalInterest.toFixed(2)}`, 20, startY + lineHeight * 6);
  doc.text(`Total Payment: £${totalPayment.toFixed(2)}`, 20, startY + lineHeight * 7);

  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("Generated by Loan-Calculator.co.uk", 105, 280, { align: "center" });
  
  // Save the PDF
  doc.save("personal-loan-summary.pdf");
};

export const generateCarLoanPDF = (
  loanAmount: string,
  interestRate: string,
  loanTerm: string,
  monthlyPayment: number,
  totalPayment: number,
  totalInterest: number
) => {
  const doc = new jsPDF();
  
  // Add logo and header
  doc.setFontSize(24);
  doc.setTextColor(51, 65, 85); // slate-700
  doc.text("Car-Loans.co.uk", 105, 20, { align: "center" });
  
  // Add decorative line
  doc.setDrawColor(99, 102, 241); // indigo-500
  doc.setLineWidth(0.5);
  doc.line(20, 25, 190, 25);

  // Add car loan details
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Car Loan Summary", 105, 40, { align: "center" });

  doc.setFontSize(12);
  const startY = 60;
  const lineHeight = 10;

  doc.text(`Car Loan Amount: £${Number(loanAmount).toLocaleString()}`, 20, startY);
  doc.text(`Interest Rate: ${interestRate}%`, 20, startY + lineHeight);
  doc.text(`Loan Term: ${loanTerm} years`, 20, startY + lineHeight * 2);
  
  // Add results
  doc.setFontSize(14);
  doc.text("Payment Details", 20, startY + lineHeight * 4);
  
  doc.setFontSize(12);
  doc.text(`Monthly Payment: £${monthlyPayment.toFixed(2)}`, 20, startY + lineHeight * 5);
  doc.text(`Total Interest: £${totalInterest.toFixed(2)}`, 20, startY + lineHeight * 6);
  doc.text(`Total Payment: £${totalPayment.toFixed(2)}`, 20, startY + lineHeight * 7);

  // Add footer with logo
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("Generated by Car-Loans.co.uk", 105, 280, { align: "center" });
  
  // Save the PDF
  doc.save("car-loan-summary.pdf");
};